#!/usr/bin/env bash

set -euo pipefail

if ! rbw unlocked >/dev/null 2>&1; then
    if ! rbw unlock; then
        exit
    fi
fi

RESULT=$(rbw list | fzf --height=100%)

if [ -n "$RESULT" ]; then
    PASS=$(rbw get "$RESULT")
    wl-copy "$PASS"
    notify-send "Password Picker" "Entry copied to system clipboard"
fi
