[all]
bash = "~"
bat = ".config/bat"
bottom = ".config/bottom"
fd = ".config/fd"
fish = ".config/fish"
foot = ".config/foot"
fuzzel = ".config/fuzzel"
git = ".config/git"
gitui = ".config/gitui"
"gtk/gtk-3.0-settings.ini" = ".config/gtk-3.0/settings.ini"
"gtk/gtk-4.0-settings.ini" = ".config/gtk-4.0/settings.ini"
"icons/default/index.theme" = ".icons/default/index.theme"
ideavim = ".config/ideavim"
kitty = ".config/kitty"
mako = ".config/mako"
MangoHud = ".config/MangoHud"
niri = ".config/niri"
wallpapers = "Pictures/Wallpapers"
ripgrep = ".config/ripgrep"
scripts = ".config/scripts"
"ssh/config" = ".ssh/config"
sway = ".config/sway"
swaynag = ".config/swaynag"
tmux = ".config/tmux"
tmuxp = ".config/tmuxp"
waybar = ".config/waybar"
"x11/.Xresources" = ".Xresources"
xdg = ".config"
yazi = ".config/yazi"
profile = "~"
