[agentic-nvim]
src.git = "https://github.com/carlos-algms/agentic.nvim"
fetch.github = "carlos-algms/agentic.nvim"
src.branch = "main"

[agentic-skills]
src.git = "https://github.com/oahlen/agentic-skills"
fetch.github = "oahlen/agentic-skills"
src.branch = "main"

[aurora-nvim]
src.git = "https://github.com/oahlen/aurora.nvim"
fetch.github = "oahlen/aurora.nvim"
src.branch = "main"

[base16-theme]
src.git = "https://github.com/oahlen/base16.tmTheme"
fetch.github = "oahlen/base16.tmTheme"
src.branch = "main"

[nixGL]
src.git = "https://github.com/nix-community/nixGL"
fetch.github = "nix-community/nixGL"
src.branch = "main"

[shellcheck-nvim]
src.git = "https://github.com/pablos123/shellcheck.nvim"
fetch.github = "pablos123/shellcheck.nvim"
src.branch = "main"
