# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentic-nvim = {
    pname = "agentic-nvim";
    version = "37a53a7ad074d12740d90eab9efc0c01e6155864";
    src = fetchFromGitHub {
      owner = "carlos-algms";
      repo = "agentic.nvim";
      rev = "37a53a7ad074d12740d90eab9efc0c01e6155864";
      fetchSubmodules = false;
      sha256 = "sha256-olrSbH2Alw7IUPMJH17RV7cmKvIL1BPMPpKCWndF22U=";
    };
    date = "2026-06-28";
  };
  agentic-skills = {
    pname = "agentic-skills";
    version = "fe08fac55cc40f7428abf18e422631fd00f2c2b7";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "agentic-skills";
      rev = "fe08fac55cc40f7428abf18e422631fd00f2c2b7";
      fetchSubmodules = false;
      sha256 = "sha256-UowdqBvCJT3tv4wibiODeGi2EI2jChDWxt0w5tbVbL0=";
    };
    date = "2026-06-24";
  };
  aurora-nvim = {
    pname = "aurora-nvim";
    version = "04f80cc6ec62c4b0e61dbdd5895fc84b33702bd0";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "aurora.nvim";
      rev = "04f80cc6ec62c4b0e61dbdd5895fc84b33702bd0";
      fetchSubmodules = false;
      sha256 = "sha256-9ceV20LUngmWNNOByS+uxwTTWj8Giw2kNhQihb4S9Ww=";
    };
    date = "2026-06-30";
  };
  base16-theme = {
    pname = "base16-theme";
    version = "83fe109c88668d1ae78851fa66c1c06957d82c52";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "base16.tmTheme";
      rev = "83fe109c88668d1ae78851fa66c1c06957d82c52";
      fetchSubmodules = false;
      sha256 = "sha256-1L9m48twPsBAVCmWnxggFjiLgDDHJz92lNfW+UBtTxs=";
    };
    date = "2026-06-22";
  };
  nixGL = {
    pname = "nixGL";
    version = "b6105297e6f0cd041670c3e8628394d4ee247ed5";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nixGL";
      rev = "b6105297e6f0cd041670c3e8628394d4ee247ed5";
      fetchSubmodules = false;
      sha256 = "sha256-fbRQzIGPkjZa83MowjbD2ALaJf9y6KMDdJBQMKFeY/8=";
    };
    date = "2025-11-02";
  };
  shellcheck-nvim = {
    pname = "shellcheck-nvim";
    version = "ee40e705ea61a4d790907c93cd01cc52480351fa";
    src = fetchFromGitHub {
      owner = "pablos123";
      repo = "shellcheck.nvim";
      rev = "ee40e705ea61a4d790907c93cd01cc52480351fa";
      fetchSubmodules = false;
      sha256 = "sha256-1rfEtD+II1uh6cn/dBxwGKxNFUwgoKXWtcJHIi6ydy4=";
    };
    date = "2025-04-07";
  };
}
