# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentic-nvim = {
    pname = "agentic-nvim";
    version = "a19fee663aa8be5f46f0af6fc0b46427b0e75cf2";
    src = fetchFromGitHub {
      owner = "carlos-algms";
      repo = "agentic.nvim";
      rev = "a19fee663aa8be5f46f0af6fc0b46427b0e75cf2";
      fetchSubmodules = false;
      sha256 = "sha256-ZT1ME4E8jwC6DPLVpEgCudL8go91q7PkfJn5ylajmYA=";
    };
    date = "2026-06-11";
  };
  aurora-nvim = {
    pname = "aurora-nvim";
    version = "48a313ee79c4720084be6e12aa8a4d56d8df35cf";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "aurora.nvim";
      rev = "48a313ee79c4720084be6e12aa8a4d56d8df35cf";
      fetchSubmodules = false;
      sha256 = "sha256-IUSoMWwNiigMjOoEiKJYGzazN7HKwNnAmiVAWwj68Qw=";
    };
    date = "2026-06-16";
  };
  base16-theme = {
    pname = "base16-theme";
    version = "83fe109c88668d1ae78851fa66c1c06957d82c52";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "base16.tmTheme";
      rev = "83fe109c88668d1ae78851fa66c1c06957d82c52";
      fetchSubmodules = false;
      sha256 = "sha256-1L9m48twPsBAVCmWnxggFjiLgDDHJz92lNfW+UBtTxs=";
    };
    date = "2026-06-22";
  };
  nixGL = {
    pname = "nixGL";
    version = "b6105297e6f0cd041670c3e8628394d4ee247ed5";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nixGL";
      rev = "b6105297e6f0cd041670c3e8628394d4ee247ed5";
      fetchSubmodules = false;
      sha256 = "sha256-fbRQzIGPkjZa83MowjbD2ALaJf9y6KMDdJBQMKFeY/8=";
    };
    date = "2025-11-02";
  };
  shellcheck-nvim = {
    pname = "shellcheck-nvim";
    version = "ee40e705ea61a4d790907c93cd01cc52480351fa";
    src = fetchFromGitHub {
      owner = "pablos123";
      repo = "shellcheck.nvim";
      rev = "ee40e705ea61a4d790907c93cd01cc52480351fa";
      fetchSubmodules = false;
      sha256 = "sha256-1rfEtD+II1uh6cn/dBxwGKxNFUwgoKXWtcJHIi6ydy4=";
    };
    date = "2025-04-07";
  };
}
