# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentic-nvim = {
    pname = "agentic-nvim";
    version = "a19fee663aa8be5f46f0af6fc0b46427b0e75cf2";
    src = fetchFromGitHub {
      owner = "carlos-algms";
      repo = "agentic.nvim";
      rev = "a19fee663aa8be5f46f0af6fc0b46427b0e75cf2";
      fetchSubmodules = false;
      sha256 = "sha256-ZT1ME4E8jwC6DPLVpEgCudL8go91q7PkfJn5ylajmYA=";
    };
    date = "2026-06-11";
  };
  agentic-skills = {
    pname = "agentic-skills";
    version = "fe08fac55cc40f7428abf18e422631fd00f2c2b7";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "agentic-skills";
      rev = "fe08fac55cc40f7428abf18e422631fd00f2c2b7";
      fetchSubmodules = false;
      sha256 = "sha256-UowdqBvCJT3tv4wibiODeGi2EI2jChDWxt0w5tbVbL0=";
    };
    date = "2026-06-24";
  };
  aurora-nvim = {
    pname = "aurora-nvim";
    version = "562614f2028a3d232e9af96ba227d0eb16e2cf54";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "aurora.nvim";
      rev = "562614f2028a3d232e9af96ba227d0eb16e2cf54";
      fetchSubmodules = false;
      sha256 = "sha256-/l3gSK+EmymlyIdnQyTK4Tch6254cppG7Epo4LGS/iU=";
    };
    date = "2026-06-26";
  };
  base16-theme = {
    pname = "base16-theme";
    version = "83fe109c88668d1ae78851fa66c1c06957d82c52";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "base16.tmTheme";
      rev = "83fe109c88668d1ae78851fa66c1c06957d82c52";
      fetchSubmodules = false;
      sha256 = "sha256-1L9m48twPsBAVCmWnxggFjiLgDDHJz92lNfW+UBtTxs=";
    };
    date = "2026-06-22";
  };
  nixGL = {
    pname = "nixGL";
    version = "b6105297e6f0cd041670c3e8628394d4ee247ed5";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nixGL";
      rev = "b6105297e6f0cd041670c3e8628394d4ee247ed5";
      fetchSubmodules = false;
      sha256 = "sha256-fbRQzIGPkjZa83MowjbD2ALaJf9y6KMDdJBQMKFeY/8=";
    };
    date = "2025-11-02";
  };
  shellcheck-nvim = {
    pname = "shellcheck-nvim";
    version = "ee40e705ea61a4d790907c93cd01cc52480351fa";
    src = fetchFromGitHub {
      owner = "pablos123";
      repo = "shellcheck.nvim";
      rev = "ee40e705ea61a4d790907c93cd01cc52480351fa";
      fetchSubmodules = false;
      sha256 = "sha256-1rfEtD+II1uh6cn/dBxwGKxNFUwgoKXWtcJHIi6ydy4=";
    };
    date = "2025-04-07";
  };
}
