#!/usr/bin/env bash

set -euo pipefail

PICKER="fuzzel -d --with-nth=1 --accept-nth=2 --nth-delimiter=:"
TERMINAL="foot -a foot-floating -e"

options=(
    "Bluetooth Management:bluetui"
    "Connection Manager:nmtui"
    "Process Monitor:btop"
    "Volume Control:wiremix"
)

RESULT=$(printf '%s\n' "${options[@]}" | $PICKER) || true

if [ -n "$RESULT" ]; then
    exec $TERMINAL "$RESULT"
fi
