#!/usr/bin/env bash

SERVICE="$1.service"

if systemctl --user is-active --quiet "$SERVICE"; then
    systemctl --user stop "$SERVICE"
    notify-send "$1" "Service stopped"
else
    systemctl --user start "$SERVICE"
    notify-send "$1" "Service started"
fi
