includes = [
  "../../config/default.toml",
  "../../config/graphical.toml"
  "../../config/opencode.toml",
]

[files]
"niri" = "~/.config/niri"
"scripts" = "~/.config/scripts"
"Wallpapers" = "~/Pictures/Wallpapers"
