[files]
"bash" = "~"
"bat" = "~/.config/bat"
"bottom" = "~/.config/bottom"
"fd" = "~/.config/fd"
"fish" = "~/.config/fish"
"git" = "~/.config/git"
"gitui" = "~/.config/gitui"
"nvim" = "~/.config/nvim"
"opencode" = "~/.config/opencode"
"profile" = "~"
"ripgrep" = "~/.config/ripgrep"
"scripts" = "~/.config/scripts"
"ssh" = "~/.ssh"
"tmux" = "~/.config/tmux"
"tmuxp" = "~/.config/tmuxp"
"xdg" = "~/.config"
"yazi" = "~/.config/yazi"
