[files]
"foot" = "~/.config/foot"
"fuzzel" = "~/.config/fuzzel"
"ideavim" = "~/.config/ideavim"
"mako" = "~/.config/mako"
"MangoHud" = "~/.config/MangoHud"
"niri" = "~/.config/niri"
"swaylock" = "~/.config/swaylock"
"waybar" = "~/.config/waybar"
"wlr-which-key" = "~/.config/wlr-which-key"
