# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentic-nvim = {
    pname = "agentic-nvim";
    version = "b6529a4749ee72ba64e40401e4b25d0ef7cdb81e";
    src = fetchFromGitHub {
      owner = "carlos-algms";
      repo = "agentic.nvim";
      rev = "b6529a4749ee72ba64e40401e4b25d0ef7cdb81e";
      fetchSubmodules = false;
      sha256 = "sha256-G1g+5jUmAyWBh3PBMGff27CkfUyJTdoY+gRlmcVf/OM=";
    };
    date = "2026-05-29";
  };
  aurora-nvim = {
    pname = "aurora-nvim";
    version = "c1046ca8a278c9af5da5b0a3b803d3d2187f224d";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "aurora.nvim";
      rev = "c1046ca8a278c9af5da5b0a3b803d3d2187f224d";
      fetchSubmodules = false;
      sha256 = "sha256-3yUOr9bXdPEa8eunUOLrkFzCUJql0X1QOeacMyOQNME=";
    };
    date = "2026-06-06";
  };
  shellcheck-nvim = {
    pname = "shellcheck-nvim";
    version = "ee40e705ea61a4d790907c93cd01cc52480351fa";
    src = fetchFromGitHub {
      owner = "pablos123";
      repo = "shellcheck.nvim";
      rev = "ee40e705ea61a4d790907c93cd01cc52480351fa";
      fetchSubmodules = false;
      sha256 = "sha256-1rfEtD+II1uh6cn/dBxwGKxNFUwgoKXWtcJHIi6ydy4=";
    };
    date = "2025-04-07";
  };
}
