# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentic-nvim = {
    pname = "agentic-nvim";
    version = "a19fee663aa8be5f46f0af6fc0b46427b0e75cf2";
    src = fetchFromGitHub {
      owner = "carlos-algms";
      repo = "agentic.nvim";
      rev = "a19fee663aa8be5f46f0af6fc0b46427b0e75cf2";
      fetchSubmodules = false;
      sha256 = "sha256-ZT1ME4E8jwC6DPLVpEgCudL8go91q7PkfJn5ylajmYA=";
    };
    date = "2026-06-11";
  };
  aurora-nvim = {
    pname = "aurora-nvim";
    version = "1dffeb24379095e60a2d059dbff6c9a792e1c0ee";
    src = fetchFromGitHub {
      owner = "oahlen";
      repo = "aurora.nvim";
      rev = "1dffeb24379095e60a2d059dbff6c9a792e1c0ee";
      fetchSubmodules = false;
      sha256 = "sha256-XFz5sUE4OTxe2Hm879hD1r0kejT358D5QSP4B7KOV40=";
    };
    date = "2026-06-12";
  };
  shellcheck-nvim = {
    pname = "shellcheck-nvim";
    version = "ee40e705ea61a4d790907c93cd01cc52480351fa";
    src = fetchFromGitHub {
      owner = "pablos123";
      repo = "shellcheck.nvim";
      rev = "ee40e705ea61a4d790907c93cd01cc52480351fa";
      fetchSubmodules = false;
      sha256 = "sha256-1rfEtD+II1uh6cn/dBxwGKxNFUwgoKXWtcJHIi6ydy4=";
    };
    date = "2025-04-07";
  };
}
