includes = [
  "../../config/default.toml",
  "../../config/direnv.toml",
  "../../config/graphical.toml"
]

[files]
"niri" = "~/.config/niri"
"scripts" = "~/.config/scripts"
"Wallpapers" = "~/Pictures/Wallpapers"
