#!/bin/sh

BRANCH="${1:-master}"
printf "Displaying kernel versions from \033[1;35m%s\033[0m\n" "$BRANCH"

URL="https://raw.githubusercontent.com/NixOS/nixpkgs/refs/heads/${BRANCH}/pkgs/os-specific/linux/kernel/kernels-org.json"
curl -s "$URL" | jq -r 'to_entries[] | "\u001b[1m\(.key):\u001b[0m \(.value.version)"'

ZEN_URL="https://raw.githubusercontent.com/NixOS/nixpkgs/refs/heads/${BRANCH}/pkgs/os-specific/linux/kernel/zen-kernels.nix"
printf "\033[1mZen: \033[0m"
curl -s "$ZEN_URL" | grep -o 'version = "[^"]*"' | grep -o '"[^"]*"' | tr -d '"'
